"""config item core models

Revision ID: 594335bf32be
Revises: 1050c14d1dba
Create Date: 2026-08-16 14:59:27.831153

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '594335bf32be'
down_revision = '1050c14d1dba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('config_item_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('config_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_item_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['config_item_type_id'], ['config_item_types.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_item_type_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('field_type', sa.String(length=16), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('options', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('archived', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['config_item_type_id'], ['config_item_types.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_item_type_id', 'name', name='uq_field_definition_type_name')
    )
    op.create_table('change_log_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_item_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=24), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('changed_by_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['config_item_id'], ['config_items.id'], ),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('config_item_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('target_id', sa.Integer(), nullable=False),
    sa.Column('relationship_type', sa.String(length=32), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('source_id != target_id', name='ck_relationship_no_self_reference'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['config_items.id'], ),
    sa.ForeignKeyConstraint(['target_id'], ['config_items.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_id', 'target_id', 'relationship_type', name='uq_relationship_source_target_type')
    )
    op.create_table('field_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('config_item_id', sa.Integer(), nullable=False),
    sa.Column('field_definition_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['config_item_id'], ['config_items.id'], ),
    sa.ForeignKeyConstraint(['field_definition_id'], ['field_definitions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('config_item_id', 'field_definition_id', name='uq_field_value_item_field')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_values')
    op.drop_table('config_item_relationships')
    op.drop_table('change_log_entries')
    op.drop_table('field_definitions')
    op.drop_table('config_items')
    op.drop_table('config_item_types')
    # ### end Alembic commands ###
