"""add active flag to users

Revision ID: 6168103ffca4
Revises: cc7ae12e5182
Create Date: 2026-09-13 17:27:05.126416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6168103ffca4'
down_revision = 'cc7ae12e5182'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default='1', sonst lehnt MariaDB die NOT-NULL-Spalte bei bestehenden Zeilen ab.
        batch_op.add_column(sa.Column('active', sa.Boolean(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('active')

    # ### end Alembic commands ###
