"""add password reset counter to users

Revision ID: 7ca37d988535
Revises: 6168103ffca4
Create Date: 2026-09-15 01:21:48.905705

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ca37d988535'
down_revision = '6168103ffca4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        # server_default='0', sonst lehnt MariaDB die NOT-NULL-Spalte bei bestehenden Zeilen ab.
        batch_op.add_column(sa.Column('password_reset_counter', sa.Integer(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('password_reset_counter')

    # ### end Alembic commands ###
