"""add optimistic locking version to config items

Revision ID: cc7ae12e5182
Revises: 594335bf32be
Create Date: 2026-09-06 15:50:18.204018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cc7ae12e5182'
down_revision = '594335bf32be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.Integer(), nullable=False, server_default='1'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('config_items', schema=None) as batch_op:
        batch_op.drop_column('version')

    # ### end Alembic commands ###
